### ISSUE TITLE
Adding linting for better developer experience and consitent code quality.

### ISSUE THREAD

**Issue by PradhumnaPancholi** [BanklessDAO/bankless-loans#20]
Implementing linting with eslint and prettiier. Airbnb way is preferred and more fine-tuned settings are : 

- [ ] Single Quotes
- [ ] No semicolon

**Comment by daniel-ivanco** [comment]
Hello @PradhumnaPancholi , I was freshly added to Bankless DAO dev guild (my handle is xivanc01#3548), if possible I'd be happy to have a look at this task.

**Comment by PradhumnaPancholi** [comment]
Hey Daniel, great to see you here. Yeah sure, go ahead

**Comment by daniel-ivanco** [comment]
> Hey Daniel, great to see you here. Yeah sure, go ahead

Hi @PradhumnaPancholi, I have created a branch with eslint related changes, but I can't push it due to denied permissions. How would you like me to proceed?

**Comment by PradhumnaPancholi** [comment]
Just sent you an invite and gave write permissions

**Comment by daniel-ivanco** [comment]
Thanks, here is the PR https://github.com/BanklessDAO/liquity-frontend/pull/28

**Comment by geositta** [comment]
Merged Husky and Lint-staged change to run linting on every commit. Does not require any local config on the part of the developer since it is local-dev agnostic.
