### ISSUE TITLE
Exposed API Key

### ISSUE THREAD

**Issue by 0xNSHuman** [BanklessDAO/bankless-loans#33]
Since a lot of Infura API's functionality can be requested with the API key only (without need for a Secret), I think the key is sensitive enough, and anyone possessing it can technically drain quotas in the Infura account and/or trigger payment method charges for extra usage.

https://github.com/BanklessDAO/bankless-loans/blob/2442bafed8e396ace0a04de36045a383a4aa6694/constants/index.ts#L1

**Comment by vladaverin24** [comment]
I've created an `.env` file to store keys like that in my current branch, I'd relocate this one there as well.

**Comment by PradhumnaPancholi** [comment]
Thanks

**Comment by geositta** [comment]
Thank you, This was remove in separate PR.
