### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by PradhumnaPancholi** [BanklessDAO/bankless-loans#4]
The task requires developing the landing page according to Figma design.

**Comment by zberwaldt** [comment]
While building the theme overrides for Chakra UI, I am slowly building a mock-up of the landing page from the Figma design. I have not been committing to my branch. I thought I'd just put it out there.

**Comment by geositta** [comment]
We are removing the concept of a landing page in new design to follow a simpler Uniswap UI flow.
